from .anaconda import Anaconda
from .bass import Bass
from .cobra import Cobra
from .copperhead import Copperhead
from .donkey import Donkey
from .goat import Goat
from .gorilla import Gorilla
from .great_white import Great_White
from .llama import Llama
from .mini_horse import Mini_Horse
from .perch import Perch
from .piranha import Piranha
from .platypus import Platypus
from .rattle_snake import Rattle_Snake
from .viper import Viper
from .animals import Animal
